apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-agentscape-backend-storage-pv
  labels:
    usage: prod-agentscape-backend-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: prod-agentscape-backend-storage-secret
    shareName: proagebacshare
    readOnly: false
