apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-agentscape-backend-storage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      usage: prod-agentscape-backend-storage-pv
